### PR TITLE
Code review

### PR DESCRIPTION
**Pull request by mmgallai**

### CODE REVIEW

**Review by nagatharun — COMMENTED** [review]
Lets make more changes

**Review by jagruthreddy — CHANGES_REQUESTED** [review]
Making them into their classes is the best coding practice. Looks good

**Review by jagruthreddy — CHANGES_REQUESTED** [review]
I see delete button 2 times. Check code again

**Comment by jagruthreddy** [comment]
Do not push cache.

**Review by jagruthreddy — APPROVED** [review]
Thank you for the update on duplicate delete functionality.

**Review by jagruthreddy — CHANGES_REQUESTED** [review]
Change it, this code has issues.

**Review by jagruthreddy — APPROVED** [review]
It's solved. Thank you.

**Pull request merged**
